# Generated by Django 4.2.11 on 2026-02-12 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('TRANSFER', 'Transferencia'), ('ADJUST', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo total')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha procesado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='users.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='warehouses.warehouse', verbose_name='Bodega origen')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='warehouses.warehouse', verbose_name='Bodega destino')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('TRANSFER', 'Transferencia'), ('ADJUST', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('input_quantity', models.IntegerField(default=0, verbose_name='Cantidad entrada')),
                ('output_quantity', models.IntegerField(default=0, verbose_name='Cantidad salida')),
                ('balance_quantity', models.IntegerField(verbose_name='Saldo cantidad')),
                ('input_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor entrada')),
                ('output_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor salida')),
                ('balance_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo valor')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo unitario')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='users.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to=settings.AUTH_USER_MODEL)),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='movements.movement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['movement_type'], name='movements_m_movemen_1b2557_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['status'], name='movements_m_status_9c3411_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['product', 'created_at'], name='movements_m_product_f3ace9_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['warehouse_from', 'warehouse_to'], name='movements_m_warehou_5c2614_idx'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['product', 'created_at'], name='movements_k_product_eac9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['warehouse', 'created_at'], name='movements_k_warehou_4f0f58_idx'),
        ),
    ]
