# Generated by Django 4.2.11 on 2026-02-12 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('warehouses', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('min_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
                ('max_stock', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock máximo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en bodega')),
                ('last_movement', models.DateTimeField(blank=True, null=True, verbose_name='Último movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='users.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'indexes': [models.Index(fields=['product', 'warehouse'], name='inventory_i_product_f6b65e_idx'), models.Index(fields=['quantity'], name='inventory_i_quantit_ef61d1_idx')],
                'unique_together': {('company', 'product', 'warehouse')},
            },
        ),
    ]
